name: Build and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Run tests
      run: flutter test
    
    - name: Build APK
      run: flutter build apk --release
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: |
        sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
        xcode-select -p
        xcodebuild -version
        echo "Available Xcode installations:"
        ls -la /Applications/ | grep Xcode
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
    
    - name: Verify Flutter and show doctor
      run: |
        flutter --version
        flutter doctor -v
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Clean previous builds
      run: |
        flutter clean
        cd ios
        rm -rf build/ || true
        rm -rf Pods/ || true
        rm -rf .symlinks/ || true
        rm Podfile.lock || true
    
    - name: Install CocoaPods dependencies
      run: |
        cd ios
        echo "Installing CocoaPods..."
        pod --version
        pod install --verbose
        
        echo "Checking Podfile.lock:"
        head -20 Podfile.lock
    
    - name: Build iOS for Simulator
      run: |
        echo "Available iOS Simulators:"
        xcrun simctl list devices | grep "iPhone 15" | head -3
        
        echo "Available iOS SDKs:"
        xcodebuild -showsdks | grep -E "(iphoneos|iphonesimulator)"
        
        cd ios
        
        # Ensure deployment target consistency
        echo "Setting iOS deployment target to 12.0..."
        sed -i.bak 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*/IPHONEOS_DEPLOYMENT_TARGET = 12.0/g' Runner.xcodeproj/project.pbxproj
        
        # Build for iOS Simulator with explicit settings
        echo "Starting iOS Simulator build..."
        xcodebuild -workspace Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          -derivedDataPath build \
          IPHONEOS_DEPLOYMENT_TARGET=12.0 \
          ONLY_ACTIVE_ARCH=YES \
          build
          
        echo "iOS build completed successfully!"
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-simulator-build
        path: |
          ios/build/
          ios/Podfile.lock
        if-no-files-found: warn