name: Build and Deploy to App Stores

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        cache: true
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build Android APK
      run: flutter build apk --release
      
    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    name: Build iOS (Simulator)
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      run: |
        sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
        xcodebuild -version
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        cache: true
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Fix iOS deployment target
      run: |
        export IPHONEOS_DEPLOYMENT_TARGET=12.0
        sed -i.bak 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*/IPHONEOS_DEPLOYMENT_TARGET = 12.0/g' ios/Runner.xcodeproj/project.pbxproj
        
    - name: Build iOS (Simulator)
      run: flutter build ios --simulator --no-codesign
      
    - name: Create iOS Archive
      run: |
        cd build/ios/iphonesimulator
        zip -r Runner.zip Runner.app
        
    - name: Upload iOS Build
      uses: actions/upload-artifact@v4
      with:
        name: ios-simulator-build
        path: build/ios/iphonesimulator/Runner.zip