name: Build Pipeline Test

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Test type'
        required: true
        default: 'both'
        type: choice
        options:
          - android-only
          - ios-only
          - both

jobs:
  test-android:
    if: inputs.test_type == 'android-only' || inputs.test_type == 'both'
    name: Test Android Build
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.2'
        cache: true
        
    - name: Quick Android Test
      run: |
        flutter doctor -v
        flutter pub get
        flutter build apk --debug --verbose || echo "❌ Android build failed"
        
  test-ios:
    if: inputs.test_type == 'ios-only' || inputs.test_type == 'both'
    name: Test iOS Build
    runs-on: macos-14
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer 2>/dev/null || \
        sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer 2>/dev/null || \
        echo "Using default Xcode"
        xcodebuild -version
        
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.2'
        cache: true
        
    - name: Quick iOS Test
      run: |
        flutter doctor -v
        flutter pub get
        cd ios && pod install --repo-update && cd ..
        flutter build ios --no-codesign --verbose || echo "❌ iOS build failed"