name: Build and Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.2'
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
        
    - name: Cache Pub Dependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.PUB_CACHE }}
          ~/.pub-cache
          **/.dart_tool
        key: pub-cache-android-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          pub-cache-android-
        
    - name: Install dependencies
      run: |
        flutter doctor -v
        flutter pub get
      
    - name: Build Android APK
      run: flutter build apk --release
      
    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    name: Build iOS (Simulator)
    runs-on: macos-14
    timeout-minutes: 45
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      run: |
        sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer
        xcodebuild -version
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.2'
        cache: true
        cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
        
    - name: Cache Pub Dependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.PUB_CACHE }}
          ~/.pub-cache
          **/.dart_tool
        key: pub-cache-ios-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          pub-cache-ios-
          
    - name: Cache iOS Pods
      uses: actions/cache@v4
      with:
        path: ios/Pods
        key: pods-simulator-${{ hashFiles('ios/Podfile.lock') }}
        restore-keys: |
          pods-simulator-
        
    - name: Install dependencies
      run: |
        flutter doctor -v
        flutter pub get
        cd ios && pod install --repo-update && cd ..
      
    - name: Fix iOS deployment target
      run: |
        export IPHONEOS_DEPLOYMENT_TARGET=16.0
        sed -i.bak 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*/IPHONEOS_DEPLOYMENT_TARGET = 16.0/g' ios/Runner.xcodeproj/project.pbxproj
        
    - name: Build iOS (Simulator)
      run: flutter build ios --simulator --no-codesign
      
    - name: Create iOS Archive
      run: |
        cd build/ios/iphonesimulator
        zip -r Runner.zip Runner.app
        
    - name: Upload iOS Build
      uses: actions/upload-artifact@v4
      with:
        name: ios-simulator-build
        path: build/ios/iphonesimulator/Runner.zip