name: Test Secrets Configuration

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Which secrets to test'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - ios-only
        - android-only

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Check iOS Secrets
      if: github.event.inputs.test_type == 'all' || github.event.inputs.test_type == 'ios-only'
      run: |
        echo "🍎 Testing iOS Secrets..."
        
        # Check if secrets exist (without revealing content)
        if [ -z "${{ secrets.IOS_CERTIFICATE_BASE64 }}" ]; then
          echo "❌ IOS_CERTIFICATE_BASE64 is missing"
        else
          echo "✅ IOS_CERTIFICATE_BASE64 exists (${#IOS_CERT} chars)"
        fi
        
        if [ -z "${{ secrets.IOS_CERTIFICATE_PASSWORD }}" ]; then
          echo "❌ IOS_CERTIFICATE_PASSWORD is missing"
        else
          echo "✅ IOS_CERTIFICATE_PASSWORD exists"
        fi
        
        if [ -z "${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}" ]; then
          echo "❌ IOS_PROVISIONING_PROFILE_BASE64 is missing"
        else
          echo "✅ IOS_PROVISIONING_PROFILE_BASE64 exists"
        fi
        
        if [ -z "${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}" ]; then
          echo "❌ APP_STORE_CONNECT_API_KEY_ID is missing"
        else
          echo "✅ APP_STORE_CONNECT_API_KEY_ID exists: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}"
        fi
        
        if [ -z "${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}" ]; then
          echo "❌ APP_STORE_CONNECT_API_ISSUER_ID is missing"
        else
          echo "✅ APP_STORE_CONNECT_API_ISSUER_ID exists: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}"
        fi
        
        if [ -z "${{ secrets.APP_STORE_CONNECT_API_KEY_BASE64 }}" ]; then
          echo "❌ APP_STORE_CONNECT_API_KEY_BASE64 is missing"
        else
          echo "✅ APP_STORE_CONNECT_API_KEY_BASE64 exists"
        fi
      env:
        IOS_CERT: ${{ secrets.IOS_CERTIFICATE_BASE64 }}

    - name: Check Android Secrets
      if: github.event.inputs.test_type == 'all' || github.event.inputs.test_type == 'android-only'
      run: |
        echo "🤖 Testing Android Secrets..."
        
        if [ -z "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" ]; then
          echo "❌ ANDROID_KEYSTORE_BASE64 is missing"
        else
          echo "✅ ANDROID_KEYSTORE_BASE64 exists"
        fi
        
        if [ -z "${{ secrets.ANDROID_KEY_ALIAS }}" ]; then
          echo "❌ ANDROID_KEY_ALIAS is missing"
        else
          echo "✅ ANDROID_KEY_ALIAS exists: ${{ secrets.ANDROID_KEY_ALIAS }}"
        fi
        
        if [ -z "${{ secrets.ANDROID_STORE_PASSWORD }}" ]; then
          echo "❌ ANDROID_STORE_PASSWORD is missing"
        else
          echo "✅ ANDROID_STORE_PASSWORD exists"
        fi
        
        if [ -z "${{ secrets.ANDROID_KEY_PASSWORD }}" ]; then
          echo "❌ ANDROID_KEY_PASSWORD is missing"
        else
          echo "✅ ANDROID_KEY_PASSWORD exists"
        fi

    - name: Test Base64 Decoding
      run: |
        echo "🔍 Testing Base64 decoding..."
        
        # Test iOS Certificate
        if [ ! -z "${{ secrets.IOS_CERTIFICATE_BASE64 }}" ]; then
          if echo "${{ secrets.IOS_CERTIFICATE_BASE64 }}" | base64 -d > /tmp/test_cert.p12 2>/dev/null; then
            echo "✅ iOS Certificate Base64 decoding successful"
            ls -la /tmp/test_cert.p12
          else
            echo "❌ iOS Certificate Base64 decoding failed"
          fi
        fi
        
        # Test API Key
        if [ ! -z "${{ secrets.APP_STORE_CONNECT_API_KEY_BASE64 }}" ]; then
          if echo "${{ secrets.APP_STORE_CONNECT_API_KEY_BASE64 }}" | base64 -d > /tmp/test_key.p8 2>/dev/null; then
            echo "✅ API Key Base64 decoding successful"
            ls -la /tmp/test_key.p8
          else
            echo "❌ API Key Base64 decoding failed"
          fi
        fi
        
        # Test Android Keystore
        if [ ! -z "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" ]; then
          if echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > /tmp/test_keystore.jks 2>/dev/null; then
            echo "✅ Android Keystore Base64 decoding successful"
            ls -la /tmp/test_keystore.jks
          else
            echo "❌ Android Keystore Base64 decoding failed"
          fi
        fi